Visual Studio/src/DevOps.LoadTest.Web/Models/CpuConsumeRequest.cs
namespace DevOps.LoadTest.Web.Models
{
    public class CpuConsumeRequest
    {
        public int Percentage { get; set; }

        public int Seconds { get; set; }
    }
}

Visual Studio/src/DevOps.LoadTest.Web/Models/MemoryConsumeRequest.cs
namespace DevOps.LoadTest.Web.Models
{
    public class MemoryConsumeRequest
    {
        public int Megabytes { get; set; }

        public int Seconds { get; set; }
    }
}

Visual Studio/src/DevOps.LoadTest.Web/Controllers/ConsumerController.cs
namespace DevOps.LoadTest.Web.Controllers
{
    using Microsoft.AspNet.Mvc;
    using Models;
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading;

    public class ConsumerController : Controller
    {
        public IActionResult Cpu()
        {
            return View(new CpuConsumeRequest { Percentage = 50, Seconds = 10 });
        }

        public IActionResult Memory()
        {
            return View(new MemoryConsumeRequest { Megabytes = 512, Seconds = 10 });
        }

        [HttpPost]
        public IActionResult ConsumeCpu(CpuConsumeRequest request)
        {
            ConsumeInAllCpus(request.Percentage, request.Seconds);
            ViewBag.Message = $"Consumed {request.Percentage:#00}% of CPU for {request.Seconds:#00} seconds";
            return View("Cpu", request);
        }

        [HttpPost]
        public IActionResult ConsumeMemory(MemoryConsumeRequest request)
        {
            ConsumeMemory(request.Megabytes, request.Seconds);
            ViewBag.Message = $"Consumed {request.Megabytes:#00}Mb of Memory for {request.Seconds:#00} seconds";
            return View("Memory", request);
        }

        private static void ConsumeInAllCpus(int percentage, int seconds)
        {
            var cancel = false;
            var threads = new List<Thread>();
            for (int i = 0; i < Environment.ProcessorCount; i++)
            {
                Thread t = new Thread(new ParameterizedThreadStart(_ => ConsumeInOneCpu(percentage, ref cancel)));
                t.Start();
                threads.Add(t);
            }

            Thread.Sleep(seconds * 1000);
            cancel = true;
        }

        private static void ConsumeInOneCpu(int percentage, ref bool cancel)
        {
            if (percentage < 0 || percentage > 100) throw new ArgumentException("percentage");

            var watch = new Stopwatch();
            watch.Start();
            while (true)
            {
                // Make the loop go on for "percentage" milliseconds then sleep the 
                // remaining percentage milliseconds. So 40% utilization means work 40ms and sleep 60ms
                if (watch.ElapsedMilliseconds > percentage)
                {
                    Thread.Sleep(100 - percentage);
                    watch.Reset();
                    watch.Start();
                }

                if (cancel) return;
            }
        }

        private static void ConsumeMemory(int megabytes, int seconds)
        {
            var list = new List<byte[]>();
            var random = new Random();
            for (var i = 0; i < megabytes; i++)
            {
                var buffer = new byte[1024 * 1024];
                random.NextBytes(buffer);
                list.Add(buffer);
            }

            Thread.Sleep(seconds * 1000);
            Trace.WriteLine(list.Count + " megabytes");
            GC.SuppressFinalize(list);
            GC.Collect();
        }
    }
}

Visual Studio/src/DevOps.LoadTest.Web/Controllers/HomeController.cs
namespace DevOps.LoadTest.Web.Controllers
{
    using Microsoft.AspNet.Mvc;

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Visual Studio/src/DevOps.LoadTest.Web/Views/Consumer/CPU.cshtml
@model DevOps.LoadTest.Web.Models.CpuConsumeRequest
@{
    ViewData["Title"] = "CPU Consumer";
}
<p>
    @ViewBag.Message
</p>
<h1>CPU Consumer</h1>
<form asp-action="ConsumeCpu" asp-controller="Consumer" method="post">
    <label for="Percentage">Percentage:</label>
    <input type="number" asp-for="Percentage" />
    <br />
    <label for="Seconds">Seconds:</label>
    <input type="number" asp-for="Seconds" /><br />
    <input type="submit" value="Send" />
</form>

Visual Studio/src/DevOps.LoadTest.Web/Views/Consumer/Memory.cshtml
@model DevOps.LoadTest.Web.Models.MemoryConsumeRequest
@{
    ViewData["Title"] = "Memory Consumer";
}
<p>
    @ViewBag.Message
</p>
<h1>Memory Consumer</h1>
<form asp-action="ConsumeMemory" asp-controller="Consumer" method="post">
    <label for="Percentage">Megabytes:</label>
    <input type="number" asp-for="Megabytes" />
    <br />
    <label for="Seconds">Seconds:</label>
    <input type="number" asp-for="Seconds" /><br />
    <input type="submit" value="Send" />
</form>

Visual Studio/src/DevOps.LoadTest.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Consumers";
}

<div class="posts">
    <div class="post">
        <h1>Load Testing and Auto-Scaling</h1>
        <p>A continuación algunas acciones que realizan un alto consumo en la máquina en la que esta aplicación esté hospedada.</p>
    </div>

    <div class="post">
        <h2 class="post-title">
            Cpu consumer
        </h2>
        <p>
            Aumenta el consumo de cpu mientras se ejecuta.
        </p>
        <a asp-action="Cpu" asp-controller="Consumer">Ir al <i>consumer</i> de CPU</a>
    </div>

    <div class="post">
        <h2 class="post-title">
            Memory consumer
        </h2>
        <p>
            Aumenta el consumo de memoria RAM mientras se ejecuta
        </p>
        <a asp-action="Memory" asp-controller="Consumer">Ir al <i>consumer</i> de Memory</a>
    </div>
</div>

Visual Studio/src/DevOps.LoadTest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevOps.LoadTest.Web</title>

    <link rel="stylesheet" href="~/css/hyde.css">
    <link rel="stylesheet" href="~/css/poole.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700|Abril+Fatface">
</head>
<body class="theme-base-08 layout-reverse">

    <div class="sidebar">
        <div class="container sidebar-sticky">

            <div class="sidebar-about">
                <div id="nav-icon">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <h1>
                    <a href="http://fernandoescolar.github.io/">
                        DevOps
                    </a>
                </h1>
                <p id="sidebar-description" class="lead">Community Roadshow by @Html.Raw("@fernandoescolar")</p>
            </div>

            <nav id="sidebar-nav" class="sidebar-nav">
                <a class="sidebar-nav-item" href="http://fernandoescolar.github.io/">Blog</a>
                <a class="sidebar-nav-item" href="http://www.github.com/fernandoescolar">Github</a>
                <a class="sidebar-nav-item" href="http://www.twitter.com/fernandoescolar">Twitter</a>
                <a class="sidebar-nav-item" href="http://www.tokiota.com">Tokiota</a>
            </nav>
            <p id="sidebar-copy">© 2016. All rights reserved.</p>
        </div>
    </div>

    <div class="content container">
        @RenderBody()
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>